# Generated by Django 4.2.5 on 2023-09-04 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conceito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Carrinho'), (2, 'Realizado'), (3, 'Pago'), (4, 'Entregue')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='camisetas', to='conceito.marca'),
        ),
        migrations.CreateModel(
            name='Bone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, default='R$', max_digits=10)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bones', to='conceito.marca')),
            ],
        ),
    ]
