# Generated by Django 4.2.5 on 2023-09-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceito', '0002_compra_alter_camiseta_marca_bone'),
    ]

    operations = [
        migrations.AddField(
            model_name='bone',
            name='cor',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bone',
            name='nome',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='camiseta',
            name='nome',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bone',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='camiseta',
            name='valor',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
