# Generated by Django 4.2.5 on 2023-09-04 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conceito', '0003_bone_cor_bone_nome_camiseta_nome_alter_bone_valor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bone',
            name='nome',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
