# Generated by Django 4.2.5 on 2023-09-13 13:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("conceito", "0004_alter_bone_nome"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Bone",
        ),
    ]
