# Generated by Django 4.2.5 on 2023-09-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
        ('conceito', '0006_camiseta_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camiseta',
            name='foto',
        ),
        migrations.AddField(
            model_name='camiseta',
            name='capa',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='uploader.image'),
        ),
    ]
